#!/usr/bin/python3
import os
from scapy.all import *
from prettytable import PrettyTable
from collections import Counter

##Defining the variables, mostly used later in the code.
pcap=rdpcap(input("What is your pcap? "))


srcIP=[]
dstIP=[]
srcdst=[]
sport=[]
dport=[]
port=[]
for pkt in pcap:
    if IP in pkt:
        try:
            srcIP.append(pkt[IP].src)
            dstIP.append(pkt[IP].dst)
            srcdst.append(pkt[IP].src + ","  + pkt[IP].dst)
            dport.append((pkt[IP].dport))
            sport.append((pkt[IP].sport))
            port.append((pkt[IP].sport))
            port.append((pkt[IP].dport))
        except:
            pass

packets=input("Remind me of the pcap again? I am just checking, because I'm insecure (coding is fun, we make jokes :) ) ")
filename=input("What would you like to name the text file of the log? It should be FILENAME.txt: ")
os.system("tshark -r " + packets + " -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e _ws.col.Info > " + filename)
os.system("head -n 30 " + filename)

print(f'\n\n\nHi there! Welcome to Log Lollygagging, also called Project LLAMA. This program will provide key information, and also allow you to parse through log files from pcaps. The program will walk you through a number of questions, for which you will need to input choices or information pertaining to what you need. The above information is a capture of the pcap you entered! It shows the fields, which are important later. \n\n\n')
def menu():
    print("---------------------------------")
    print("[1] Parse the File")
    print("[2] Frequency Tables")
    print("[3] Most Common IP/Port")
    print("[0] Exit")
    print("_________________________________")
menu()
option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))

while option != 0:
    if option == 1:
        def parsemenu():
            print("----------------------------------")
            print("[1] Packet Numbers")
            print("[2] Time")
            print("[3] Src IP")
            print("[4] Dst IP")
            print("[5] Protocol")
            print("[6] Src Ports")
            print("[7] Dst Ports")
            print("[8] Info"
            print("[9] Main Menu")
            print("__________________________________")
        
        parsemenu()
        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
        if parseoption == 6:
            reminder=input("Remind me, what is your pcap?")
            os.system("tshark -r " + reminder + " -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e _ws.col.Info -e _ws.col.Data> " + filename)
            def srcportmenu():
            print("----------------------------------")
            print("This menu is for locating the source ports, as well as their frequencies. You are able to check different parts of the logs you choose based on the menu option.\n")
            print("[1] Check all Packets")
            print("[2] Check First 10 Packets")
            print("[3] Check First {insert} Packets")
            print("[4] Check Last 10 Packets")
            print("[5] Check Last {insert} Packets")
            print("[6] 
            print("[9] Main Menu")
            print("__________________________________")

            srcportmenu()
            srcportoption=int(input("\nTime to check the Src Ports! Based on your choice, the Src Ports will appear in order from most to least frequent. How would you like to check your information?"))
            if srcportoption == 1:
                os.system("cat " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr")           
            elif srcportoption == 2:
                os.system("head " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr")
            elif srcportoption ==3:
                headnum=input("How many of the first lines do you want to display (Ex: 50)? Enter your choice here: ")
                os.system("head -n "+ headnum + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr")
            elif srcportoption == 4:
                os.system("tail " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr") 
            elif srcportoption == 5:
                tailnum=input("How many of the last lines do you want to display (Ex: 50)? Enter your choice here: ")
                os.system("tail -n "+ tailnum + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr")
            elif srcportoption == 9:
                menu()
                option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
            else:
                print(f'\nOops! Let us try, try again!')
                parsemenu()
                parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
                
        elif parseoption == 9:
            menu()
            option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
        else:
            print(f'\nDid you mean something else? Let\'s try again!')
            parsemenu()
            parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
    elif option == 2:
        cnt= Counter()
        for IP in srcIP:
            cnt[IP] += 1

        for IP in dstIP:
            cnt[IP] += 1

        dcnt= Counter()
        for IP in dstIP:
            dcnt[IP] += 1

        srcs = [*set(srcIP)]
        srctable = PrettyTable(["Src IP", "Count"])
        for ip, count in cnt.most_common():
            srctable.add_row([ip, count])
        print(srctable)

        dsttable = PrettyTable(["Dst IP", "Count"])
        for ip, count in dcnt.most_common():
            dsttable.add_row([ip, count])
        print(dsttable)

        portcnt = Counter()
        for port in sport:
            portcnt[port] +=1
        srcandporttable=PrettyTable(["Ports", "Count"])
        for port, count in portcnt.most_common():
            srcandporttable.add_row([port, count])
        print(srcandporttable)
        menu()
        option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
    elif option == 3:
        cnt1= Counter()
        for IP in srcIP:
            cnt1[IP] += 1
        dcnt1= Counter()
        for IP in dstIP:
            dcnt1[IP] += 1

        srcs = [*set(srcIP)]
        srctablemost= PrettyTable(["Src IP", "Count"])
        for ip, count in cnt1.most_common():
            srctablemost.add_row([ip, count])

        dsttablemost=PrettyTable(["Dst IP", "Count"])
        for ip, count in dcnt1.most_common():
            dsttablemost.add_row([ip, count])

        portcnt1= Counter()
        for port in sport:
            portcnt1[port] +=1
        porttablemost=PrettyTable(["Most Common Port", "Count"])
        for port, count in portcnt1.most_common():
            porttablemost.add_row([port, count])
        print(porttablemost[0])
        print(f'Your most frequent source and destination IP, as well as their frequency are Source:\n {srctablemost[0]} \n and Destination: \n{dsttablemost[0]}')
        menu()
        option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
print(f'\nAlrighty then! Thanks for visiting Log Lollygagging. We hope it helped! Happy Log Hunting')
