#!/usr/bin/python3
import os
from scapy.all import *
from prettytable import PrettyTable
from collections import Counter

##Defining the variables, mostly used later in the code.
pcap=rdpcap(input("What is your pcap? "))


srcIP=[]
dstIP=[]
srcdst=[]
sport=[]
dport=[]
port=[]
for pkt in pcap:
    if IP in pkt:
        try:
            srcIP.append(pkt[IP].src)
            dstIP.append(pkt[IP].dst)
            srcdst.append(pkt[IP].src + ","  + pkt[IP].dst)
            dport.append((pkt[IP].dport))
            sport.append((pkt[IP].sport))
            port.append((pkt[IP].sport))
            port.append((pkt[IP].dport))
        except:
            pass

packets=input("Remind me of the pcap again? I am just checking, because I'm insecure (coding is fun, we make jokes :) ) ")
filename=input("What would you like to name the text file of the log? It should be FILENAME.txt: ")
os.system("tshark -r " + packets + " -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e _ws.col.Info > " + filename)
os.system("head -n 30 " + filename)

print(f'\n\n\nHi there! Welcome to Log Lollygagging, also called Project LLAMA. This program will provide key information, and also allow you to parse through log files from pcaps. The program will walk you through a number of questions, for which you will need to input choices or information pertaining to what you need. The above information is a capture of the pcap you entered! It shows the fields, which are important later. \n\n\n')
def menu():
    print("---------------------------------")
    print("[1] Parse the File")
    print("[2] Frequency Tables")
    print("[3] Most Common IP/Port")
    print("[0] Exit")
    print("_________________________________")
menu()
option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))

while option != 0:
    if option == 1:
        def parsemenu():
            print("----------------------------------")
            print("[1] Packet Numbers")
            print("[2] Time")
            print("[3] Src IP")
            print("[4] Dst IP")
            print("[5] Protocol")
            print("[6] Other - Ports and Info")
            print("[9] Main Menu")
            print("__________________________________")
        
        parsemenu()
        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
        if parseoption == 5:
            reminder=input("Remind me, what is your pcap?")
            os.system("tshark -r " + reminder + " -T fields -e frame.number -e _ws.col.Time -e _ws.col.Source -e _ws.col.Destination -e _ws.col.Protocol -e _ws.col.Info -e _ws.col.Data> " + filename)
            catopt=input("Would you like to view the whole file and the corresponding Src Ports? Yes (type 1) or No (type 2)? ")
            if catopt == 1:
                os.system("cat " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c")
                    sortedcat=input("Do you want to sort by highest frequency to the lowest? Yes (type 1) or No (type 2)? ")
                    if sortedcat == 1:
                        os.system("cat " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c | sort -nr")
                    else:
                        print(f'Cool! Let us return')
                        parsemenu()
                        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))            
            elif catopt == 2:
                headortail=input("Would you like to view the head or tail of the file and corresponding Src Ports? Type Head or Tail")
                if headortail == 'Head' or 'head':
                    os.system("head " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c")
                    headmore=input("Do you want to see more than the first 10 lines, and corresponding Src Ports, in the file? If so, how many lines? Enter the number (Ex: 50). If not, enter N.") 
                    if headmore == [0-9]:
                        os.system("head "+ headmore + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c")
                        parsemenu()
                        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
                    else:
                        parsemenu()
                        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))             

                else:
                    os.system("tail " + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c")
                    tailmore=input("Do you want to see more than the last 10 lines, and corresponding Src Ports, in the file? If so, how many lines? Enter the number (Ex: 50) If not, enter N") 
                    if tailmore == [0-9]:
                        os.system("tail "+ tailmore + filename + "| cut -f 6 | awk '{if ($1 ~ /^[0-9]+$/) print $1}' | sort | uniq -c")
                        parsemenu()
                        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
                    else:
                        parsemenu()
                        parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
            else:
                print(f'\nOops! Let us try, try again!')
                parsemenu()
                parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
                
        elif parseoption == 9:
            menu()
            option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
        else:
            print(f'\nDid you mean something else? Let\'s try again!')
            parsemenu()
            parseoption=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
    elif option == 2:
        cnt= Counter()
        for IP in srcIP:
            cnt[IP] += 1

        for IP in dstIP:
            cnt[IP] += 1

        dcnt= Counter()
        for IP in dstIP:
            dcnt[IP] += 1

        srcs = [*set(srcIP)]
        srctable = PrettyTable(["Src IP", "Count"])
        for ip, count in cnt.most_common():
            srctable.add_row([ip, count])
        print(srctable)

        dsttable = PrettyTable(["Dst IP", "Count"])
        for ip, count in dcnt.most_common():
            dsttable.add_row([ip, count])
        print(dsttable)

        portcnt = Counter()
        for port in sport:
            portcnt[port] +=1
        srcandporttable=PrettyTable(["Ports", "Count"])
        for port, count in portcnt.most_common():
            srcandporttable.add_row([port, count])
        print(srcandporttable)
        menu()
        option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
    elif option == 3:
        cnt1= Counter()
        for IP in srcIP:
            cnt1[IP] += 1
        dcnt1= Counter()
        for IP in dstIP:
            dcnt1[IP] += 1

        srcs = [*set(srcIP)]
        srctablemost= PrettyTable(["Src IP", "Count"])
        for ip, count in cnt1.most_common():
            srctablemost.add_row([ip, count])

        dsttablemost=PrettyTable(["Dst IP", "Count"])
        for ip, count in dcnt1.most_common():
            dsttablemost.add_row([ip, count])

        portcnt1= Counter()
        for port in sport:
            portcnt1[port] +=1
        porttablemost=PrettyTable(["Most Common Port", "Count"])
        for port, count in portcnt1.most_common():
            porttablemost.add_row([port, count])
        print(porttablemost[0])
        print(f'Your most frequent source and destination IP, as well as their frequency are Source:\n {srctablemost[0]} \n and Destination: \n{dsttablemost[0]}')
        menu()
        option=int(input("\nWhat are you looking for / looking to do? Type just the number to select the option! "))
print(f'\nAlrighty then! Thanks for visiting Log Lollygagging. We hope it helped! Happy Log Hunting')
